---
title: "hw_7"
author: "Haitham Anbar, Tram Anh Hoang, Erick Njue, Maria Coronado"
output: pdf_document
date: "2022-11-05"
bibliography: lab7refs.bib
---

# Commit 1

See setup chunk in Rmd document.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, fig.width = 6.5, fig.height = 8)

library(here)
library(rio)
library(readr)
library(janitor)
library(tidyverse)
library(tinytex)


star <- import(here("data", "star.csv")) %>% 
  clean_names() %>%
  as_tibble()
  
view(star)

```


# Commit 2

These are 2 citations with (Author, year) [@young2021does; @issa2011absenteeism] followed by one more citation, [@pani2016absenteeism] and a final citation with Author (year) here @garcia2018student.

# Commit 3
```{r table-described}
scores <- star %>% group_by(sex,frl) %>% summarise(math_mean = mean(tmathss),math_sd = sd(tmathss), rdg_mean = mean(treadss), rdg_sd = sd(treadss))
scores

# scores demonstrates the mean scores and standard deviations of math and reading tests administered to children. It is separated by gender and whether or not the child is on the free or reduced lunch program(FRL)  
```


# Commit 4

```{r plot}
star %>%
  ggplot(aes(totexp,tmathss)) +
  geom_point(color="gray", size=1) +
  geom_smooth(method=lm,aes(color=frl)) +
  theme_set(theme_minimal()) +
  theme(legend.position = "bottom") +
  labs(title="Relation between teacher experience and math scores",
       subtitle = "Separate regression lines displayed by free/reduced price lunch status",
       x="Teacher Experience (years)",
       y="Total Math Scale Score") +
  scale_color_discrete(guide=guide_legend(reverse=TRUE), name="Lunch status", labels = c("Paid meals", "Free/Reduced Price Meals"))


```


\newpage

# References


